name: CI targeting-service

on:
  push:
    branches: [main]
    paths:
      - "targeting-service/**"
      - ".github/workflows/ci-targeting-service.yml"
      - ".github/workflows/_reusable-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "targeting-service/**"
      - ".github/workflows/ci-targeting-service.yml"
      - ".github/workflows/_reusable-ci.yml"
  workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/_reusable-ci.yml
    with:
      service_name: targeting-service
      language: python
      working_directory: targeting-service
      skip_aws_push: ${{ vars.SKIP_AWS_PUSH != 'false' }}
    secrets: inherit
